Repository ChingStore/ching, pull requests merged in 2019-02, with the labels that each got.

#39 Aaron/feature/need wallet
  src/Root.js
  src/components/auth/SignIn.js
  src/components/common/action-button/index.js
  src/components/common/action-button/index.style.js
  src/components/common/back-button/index.js
  src/components/common/back-button/index.style.js
  src/components/common/icon/Vector.png
  src/components/common/icon/coinbase.js
  src/components/common/icon/index.js
  src/components/common/icon/status.js
  src/components/common/icon/store-art-background.js
  src/components/common/icon/store-art-tag.js
  src/components/common/icon/trust.js
  src/components/common/wallet-button/index.js
  src/components/common/wallet-button/index.style.js
  src/components/onboarding/need-wallet/index.js
  src/components/onboarding/need-wallet/index.style.js
  src/components/store/store-welcome/index.js
  src/components/store/store-welcome/index.style.js
  src/constants/route.js
  src/constants/style.js
Labels: has dependency, ready for merge

#45 Aaron/feature/onboarding tweaks
  src/components/common/action-button/index.js
  src/components/common/action-button/index.style.js
  src/components/common/back-button/index.js
  src/components/common/back-button/index.style.js
  src/components/common/button/index.js
  src/components/common/icon/coinbase.js
  src/components/common/icon/index.js
  src/components/common/icon/status.js
  src/components/common/icon/trust.js
  src/components/common/wallet-button/index.js
  src/components/common/wallet-button/index.style.js
  src/components/onboarding/get-wallet/get-wallet-button.js
  src/components/onboarding/get-wallet/index.js
  src/components/onboarding/get-wallet/index.style.js
  src/components/onboarding/need-wallet/index.js
  src/components/root/index.js
  src/components/store/store-welcome/index.js
  src/constants/get-wallet-button.js
  src/constants/route.js
Labels: ready for merge

#46 Roman/feature/store
  .eslintrc
  flow-typed/npm/emotion-normalize_vx.x.x.js
  flow-typed/npm/react-list_vx.x.x.js
  flow-typed/npm/react-resize-detector_vx.x.x.js
  package.json
  src/components/app/App.css
  src/components/app/global.style.js
  src/components/app/index.js
  src/components/common/flex/index.js
  src/components/common/icon/edit.js
  src/components/common/icon/index.js
  src/components/common/icon/no-photo.js
  src/components/common/icon/plus.js
  src/components/common/icon/profile.js
  src/components/common/icon/sales.js
  src/components/common/icon/store.js
  src/components/common/link-button/index.js
  src/components/common/link-button/index.style.js
  src/components/inventory/index.js
  src/components/inventory/inventoryAdd.js
  src/components/nav-bar/index.js
  src/components/onboarding/sign-up-store/container/index.js
  src/components/onboarding/store-welcome/index.js
  src/components/onboarding/store-welcome/index.style.js
  src/components/root/index.js
  src/components/shopping-cart/index.js
  src/components/shopping-cart/item-row.js
  src/components/store/add-item-card.js
  src/components/store/add-item-card.style.js
  src/components/store/constants.js
  src/components/store/container/index.js
  src/components/store/container/item-card.js
  src/components/store/index.js
  src/components/store/index.style.js
  src/components/store/item-card.js
  src/components/store/item-card.style.js
  src/constants/firebase.js
  src/constants/icon.js
  src/constants/network.js
  src/constants/redux.js
  src/constants/route.js
  src/constants/style.js
  src/redux/actions/order.js
  src/redux/actions/shop.js
  src/redux/selectors.js
  yarn.lock
Labels: ready for merge

#48 Roman/feaute/routes
  src/components/app/index.js
  src/components/common/flex/index.js
  src/components/root/index.js
  src/components/routes/index.js
  src/components/store/index.js
  src/constants/firebase.js
  src/constants/route.js
Labels: ready for merge

#49 Roman/feature/transaction confirmation
  src/components/common/button/index.js
  src/components/common/button/index.style.js
  src/components/common/footer-button/index.js
  src/components/common/footer-button/index.style.js
  src/components/inventory/contemplativeLizard.jpg
  src/components/inventory/index.js
  src/components/inventory/inventoryAdd.js
  src/components/inventory/inventoryBadge.js
  src/components/inventory/inventoryCard.js
  src/components/inventory/plus.svg
  src/components/inventory/qrDialog.js
  src/components/onboarding/sign-in/index.js
  src/components/onboarding/sign-up-store/index.js
  src/components/onboarding/store-welcome/index.js
  src/components/root/index.js
  src/components/routes/index.js
  src/components/sales/index.js
  src/components/shopping-cart/confirmation.js
  src/components/shopping-cart/confirmation.style.js
  src/components/shopping-cart/container/index.js
  src/components/shopping-cart/index.js
  src/components/shopping-cart/item-row.js
  src/components/shopping-cart/qr-code.style.js
  src/components/store/container/index.js
  src/components/store/index.js
  src/constants/firebase.js
  src/constants/style.js
  src/redux/actions/shopping-cart.js
  src/utils/order.js
Labels: ready for merge

#51 Roman/feature/router.change-back-to-hash-router
  src/components/app/index.js
  src/utils/qr.js
Labels: high priority

#53 :bug: position absolute and Add button text
  src/components/add/container/index.js
  src/components/add/index.js
  src/components/add/index.style.js
  src/components/common/input-field-numerical/index.style.js
Labels: ready for merge

#57 roman/feature/app-rename
  package.json
  public/index.html
  public/manifest.json
Labels: high priority

#60 :sparkles: upload images to firestore
  flow-typed/npm/moment_v2.x.x.js
  flow-typed/npm/react-redux_v5.x.x.js
  src/redux/actions/item.js
  src/redux/store.js
Labels: ready for merge

#63 :bug: [Store NavBar Sales] Fix scrollers and shrinked items
  src/components/common/flex/index.js
  src/components/common/link-button/index.style.js
  src/components/nav-bar/index.js
  src/components/root/index.style.js
  src/components/sales/index.js
  src/components/shopping-cart/confirmation.js
  src/components/store/index.js
  src/components/store/index.style.js
  src/constants/route.js
  src/redux/actions/order.js
Labels: high priority

#71 Roman/feature/edit item
  src/components/add-edit-item/container/index.js
  src/components/add-edit-item/index.js
  src/components/add-edit-item/index.style.js
  src/components/add/container/index.js
  src/components/add/index.js
  src/components/add/index.style.js
  src/components/app/global.style.js
  src/components/common/action-button/index.js
  src/components/common/action-button/index.style.js
  src/components/common/flex/index.js
  src/components/common/footer-button/index.style.js
  src/components/common/icon/index.js
  src/components/common/icon/store-art-background.js
  src/components/common/icon/store-welcome-art.js
  src/components/common/input-field-numerical/index.js
  src/components/common/input-field-numerical/index.style.js
  src/components/common/input-field/index.js
  src/components/common/input-field/index.style.js
  src/components/common/spinner/index.js
  src/components/onboarding/home/index.js
  src/components/onboarding/home/index.style.js
  src/components/onboarding/store-welcome/container/index.js
  src/components/onboarding/store-welcome/index.js
  src/components/onboarding/store-welcome/index.style.js
  src/components/root/index.js
  src/components/root/index.style.js
  src/components/routes/index.js
  src/components/shopping-cart/index.js
  src/components/store/item-card.js
  src/components/store/item-card.style.js
  src/constants/firebase.js
  src/constants/redux.js
  src/constants/route.js
  src/redux/actions/auth.js
  src/redux/actions/item.js
  src/redux/actions/order.js
  src/redux/actions/shop.js
  src/redux/actions/shopping-cart.js
  src/redux/actions/wallet.js
  src/redux/selectors.js
  src/utils/js.js
Labels: high priority

#73 :star: [App] Add back buttons
  src/components/add-edit-item/index.js
  src/components/add-edit-item/index.style.js
  src/components/common/back-button/index.js
  src/components/onboarding/get-wallet/index.js
  src/components/onboarding/get-wallet/index.style.js
  src/components/onboarding/sign-in/index.js
  src/components/onboarding/sign-in/index.style.js
  src/components/onboarding/sign-up/index.js
  src/components/onboarding/sign-up/index.style.js
Labels: high priority

#75 Roman/feature/store.onboarding
  src/components/common/icon/index.js
  src/components/common/icon/store-art-background.js
  src/components/common/icon/store-welcome-art.js
  src/components/onboarding/sign-up-store/index.js
  src/components/onboarding/store-welcome/container/index.js
  src/components/onboarding/store-welcome/index.js
  src/components/onboarding/store-welcome/index.style.js
  src/components/routes/index.js
  src/components/store/add-item-card.js
  src/components/store/container/index.js
  src/components/store/index.js
  src/components/store/item-card.js
  src/constants/firebase.js
  src/constants/route.js
Labels: high priority

#76 Igor/feature/tx status fix
  flow-typed/npm/lodash_v4.x.x.js
  src/components/common/checkmark/index.js
  src/components/common/cross/index.js
  src/components/orders/index.js
  src/components/payment/index.js
  src/components/shopping-cart/confirmation.js
  src/components/shopping-cart/confirmation.style.js
  src/components/shopping-cart/index.js
  src/singletons/web3/injected.js
  src/utils/order.js
Labels: high priority, ready for merge

#79 Aaron/bug/add item input
  flow-typed/npm/lodash_v4.x.x.js
  flow-typed/npm/moment_v2.x.x.js
  flow-typed/npm/react-redux_v5.x.x.js
  src/components/add-edit-item/index.js
  src/components/common/input-field-numerical/index.js
Labels: high priority
